### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by allanhortle** [allanhortle/bruce#4]
- [x] Remove components
- [x] Remove Deprecated things
- [x] rename map-fetch to `mapGetIn`
- [x] rename `get-zindex to `zindex`
- [x] remove inverse
- [x] rename bruce-flood to BruceFlood
- [x] remove bruce-float
- [x] rename bruce-hide to BruceHide
- [x] rename bruce-ratio to BruceRatio
- [x] rename bruce-reset to BruceReset
- [x] rename bruce-size to BruceSize
- [x] remove bruce-verticalAlign
- [x] remove bruce-widths
- [x] remove bruce-box-model
- [x] rename bruce-breakpoint to BruceBreakpoint
- [x] rename bruce-box-sizing to BruceBoxSizing
- [x] rename bruce-ellipsis to BruceEllipsis
- [x] rename bruce-fontface to BruceFontFace
- [x] remove bruce-verticalRhythm
- [x] rename bruce-singlePropAnimation to BruceAnimationSingleProperty
- [x] remove bruce-classes-flexbox
- [x] move bruce-classes-structure to a modifier mixin
- [x] move bruce-classes-position to a modifier mixin
- [x] move bruce-classes-text to a modifier mixin
- [x] remove bruce-Input
- [x] remove bruce-component-media
- [x] remove bruce-component-table
- [x] remove bruce-arrow
- [x] remove bruce-ios
- [x] remove bruce-behave
